# Generated by Django 3.2.6 on 2021-08-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_account', models.CharField(max_length=100)),
                ('point', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.URLField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
