# Generated by Django 3.2.6 on 2021-08-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_account', models.CharField(max_length=100)),
                ('point', models.IntegerField(default=100000)),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.URLField(max_length=500)),
                ('email', models.CharField(max_length=200, null=True)),
                ('image_url', models.URLField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
